app = "db-next-js-15"
primary_region = "gru"

[build]
  image = "postgres:16"

[env]
  POSTGRES_DB = "testdb"
  POSTGRES_USER = "testuser"
  POSTGRES_PASSWORD = "testpass123"
  PGDATA = "/var/lib/postgresql/data"

[mounts]
  source = "pg_data"
  destination = "/var/lib/postgresql"

[[services]]
  internal_port = 5432
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 50

[vm]
  size = "shared-cpu-1x"
  memory = 256

[http_service]
  internal_port = 5432
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']